C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00932_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00951_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00962_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00963_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00964_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00965_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00979_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00980_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01041_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01042_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01069_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01071_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01153_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01154_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01161_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01163_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01192_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01193_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01198_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01200_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01201_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01205_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01206_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01207_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01213_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01214_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01226_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01228_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01275_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01279_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01281_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01282_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01283_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01291_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01310_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01325_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01386_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01387_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_02069_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_02090_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_02096_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09278_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09547_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09780_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09783_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09836_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09837_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09920_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09921_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_72580_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81992_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81993_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81994_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81995_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81996_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81997_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82000_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82002_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82004_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82728_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82835_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82838_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82978_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82980_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82982_3F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00932_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00951_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00962_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00963_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00964_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00965_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00979_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_00980_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01041_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01042_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01069_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01071_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01153_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01154_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01161_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01163_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01192_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01193_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01198_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01200_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01201_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01205_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01206_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01207_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01213_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01214_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01226_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01228_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01275_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01279_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01281_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01282_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01283_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01291_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01310_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01325_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01386_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_01387_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_02069_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_02090_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_02096_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09278_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09547_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09780_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09783_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09836_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09837_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09920_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_09921_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_72580_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81992_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81993_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81994_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81995_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81996_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_81997_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82000_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82002_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82004_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82728_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82835_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82838_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82978_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82980_1F.atp * -r
C:\ATP\tools\runATP.exe C:\Users\Matheus\PycharmProjects\Ferramentas\EQUIV_NP2\Modelo_rev00_82982_1F.atp * -r

pause
del *.tmp
del *.dbg
del *.bin
